In [2]:
import pandas as pd
import re
import spacy

df1 = pd.read_csv('enwiki-20170820.csv')

In [3]:
df1

,ARTICLE_ID,TITLE,SECTION_TITLE,SECTION_TEXT
0,0,Anarchism,Introduction,\n\n\n\n\n\n'''Anarchism''' is a political phi...
1,0,Anarchism,Etymology and terminology,\n\nThe term ''anarchism'' is a compound word ...
2,0,Anarchism,History,\n\n===Origins===\nWoodcut from a Diggers docu...
3,0,Anarchism,Anarchist schools of thought,\nPortrait of philosopher Pierre-Joseph Proudh...
4,0,Anarchism,Internal issues and debates,\nconsistent with anarchist values is a contro...
...,...,...,...,...
4999995,816930,Vergulde Draeck,The wrecking of the Vergulde Draeck,In 1656 the Vergulde Draeck set sail from the ...
4999996,816930,Vergulde Draeck,Arrival in Batavia,On 7 May 1656 approximately nine days after th...
4999997,816930,Vergulde Draeck,Rescue Attempts,A number of rescue attempts was conducted by t...
4999998,816930,Vergulde Draeck,Discovery of the Vergulde Draeck,The Vergulde Draeck was discovered on 13 April...
4999999,816930,Vergulde Draeck,Letters written by the survivors of the Vergul...,In March 2015 Steve Caffery of Gilt Dragon Res...

In [4]:
df1.head()

,ARTICLE_ID,TITLE,SECTION_TITLE,SECTION_TEXT
0,0,Anarchism,Introduction,\n\n\n\n\n\n'''Anarchism''' is a political phi...
1,0,Anarchism,Etymology and terminology,\n\nThe term ''anarchism'' is a compound word ...
2,0,Anarchism,History,\n\n===Origins===\nWoodcut from a Diggers docu...
3,0,Anarchism,Anarchist schools of thought,\nPortrait of philosopher Pierre-Joseph Proudh...
4,0,Anarchism,Internal issues and debates,\nconsistent with anarchist values is a contro...

In [5]:
df1.tail()

,ARTICLE_ID,TITLE,SECTION_TITLE,SECTION_TEXT
4999995,816930,Vergulde Draeck,The wrecking of the Vergulde Draeck,In 1656 the Vergulde Draeck set sail from the ...
4999996,816930,Vergulde Draeck,Arrival in Batavia,On 7 May 1656 approximately nine days after th...
4999997,816930,Vergulde Draeck,Rescue Attempts,A number of rescue attempts was conducted by t...
4999998,816930,Vergulde Draeck,Discovery of the Vergulde Draeck,The Vergulde Draeck was discovered on 13 April...
4999999,816930,Vergulde Draeck,Letters written by the survivors of the Vergul...,In March 2015 Steve Caffery of Gilt Dragon Res...

In [6]:
df1 = df1[['ARTICLE_ID', 'SECTION_TEXT']]
df1

         ARTICLE_ID                                       SECTION_TEXT
0                 0  \n\n\n\n\n\n'''Anarchism''' is a political phi...
1                 0  \n\nThe term ''anarchism'' is a compound word ...
2                 0  \n\n===Origins===\nWoodcut from a Diggers docu...
3                 0  \nPortrait of philosopher Pierre-Joseph Proudh...
4                 0  \nconsistent with anarchist values is a contro...
...             ...                                                ...
4999995      816930  In 1656 the Vergulde Draeck set sail from the ...
4999996      816930  On 7 May 1656 approximately nine days after th...
4999997      816930  A number of rescue attempts was conducted by t...
4999998      816930  The Vergulde Draeck was discovered on 13 April...
4999999      816930  In March 2015 Steve Caffery of Gilt Dragon Res...

[5000000 rows x 2 columns]

In [7]:
df = df1[0:50000]
df

       ARTICLE_ID                                       SECTION_TEXT
0               0  \n\n\n\n\n\n'''Anarchism''' is a political phi...
1               0  \n\nThe term ''anarchism'' is a compound word ...
2               0  \n\n===Origins===\nWoodcut from a Diggers docu...
3               0  \nPortrait of philosopher Pierre-Joseph Proudh...
4               0  \nconsistent with anarchist values is a contro...
...           ...                                                ...
49995        5417  Often the only binder in a forcemeat is the ph...
49996        5417                         *Ground beef\n*TourtiÃ¨re\n
49997        5417                                                 \n
49998        5417  *The Culinary Institute of America. ''Garde Ma...
49999        5418  Forseti 1680''Forseti Seated in Judgment'' (18...

[50000 rows x 2 columns]

In [8]:
def clean_text(text):
    if isinstance(text, str):
        cleaned_text = re.sub(r'\s+', ' ',text.replace('\n', ' ')).strip()
        cleaned_text = re.sub(r'[^a-zA-Z\s]', '',cleaned_text)
        cleaned_text = cleaned_text.lower()
        return cleaned_text
    else:
        return text 

df['SECTION_TEXT'] = df['SECTION_TEXT'].apply(clean_text)

C:\Users\HUZAIFA\AppData\Local\Temp\ipykernel_7384\879758537.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['SECTION_TEXT'] = df['SECTION_TEXT'].apply(clean_text)

In [9]:
df2 = df[0:5000]

In [10]:
df2

      ARTICLE_ID                                       SECTION_TEXT
0              0  anarchism is a political philosophy that advoc...
1              0  the term anarchism is a compound word composed...
2              0  origins woodcut from a diggers document by wil...
3              0  portrait of philosopher pierrejoseph proudhon ...
4              0  consistent with anarchist values is a controve...
...          ...                                                ...
4995         535                       explanatory notes references
4996         535    benedict michael les the impeachment and tri...
4997         535   white house biography   andrew johnson nation...
4998         536  aleksandr isayevich solzhenitsyn    december  ...
4999         536  early years solzhenitsyn was born in kislovods...

[5000 rows x 2 columns]

In [1]:
nlp = spacy.load("en_core_web_sm")

NameError: name 'spacy' is not defined

In [ ]:
df2.dropna(inplace=True)

def preprocess_text(text):
    doc = nlp(text)
    tokens = [token.lemma_ for token in doc if not token.is_punct and not token.is_space]
    return tokens

df2['SECTION_TEXT'] = df2['SECTION_TEXT'].apply(preprocess_text)

In [ ]:
df2

In [2]:
ind = 0
with open('result.txt', 'w') as f:
    for index, row in df2.iterrows():
        f.write(f'{row["ARTICLE_ID"]}, ')
        ind2 = row["ARTICLE_ID"]
        if ind2 == ind:
            f.write(' '.join(row["SECTION_TEXT"]))
        elif ind2!=ind:
            ind = row["ARTICLE_ID"]
            f.write(f'\n')

NameError: name 'df2' is not defined